Review the config
Try to install nvm on a thread
Update some things

diff --git a/runcoms/zshrc b/runcoms/zshrc
--- a/runcoms/zshrc
+++ b/runcoms/zshrc
@@ -17,28 +17,9 @@ alias grep="grep --color=always"
 # if phpbrew, source
 source ~/.phpbrew/bashrc 2> /dev/null
 
-# bitnami path function
-# the path is hard-coded, something should be done about that
-function bitnami-env() {
-  : ${__bitnami_path_is_on:=0}
-
-  if [[ -z "$__bitnami_path" ]]; then
-    __bitnami_path=( $(find ~/Servers -type d -name bin | grep -v htdocs) )
-  fi
-
-  if [[ "$1" == "off" ]]; then
-
-    path=( ${path:|__bitnami_path} )
-    __bitnami_path_is_on=0
-
-  elif [[ $__bitnami_path_is_on == 0 ]]; then
-
-      path=( $__bitnami_path $path )
-      __bitnami_path_is_on=1
-  fi
-}
-
 function sshmount() {
+
+  command -v sshfs || { echo 'sshfs could not be found.' && return 1; }
 
     sshfs "$1" "$2"                                  \
         -o reconnect                                 \
@@ -46,7 +27,7 @@ function sshmount() {
         -o uid=$(id -u)                              \
         -o gid=$(id -g)                              \
         -o idmap=user                                \
-        -o IdentityFile=${3:="$HOME/.ssh/id_ecdsa"}
+        -o IdentityFile=${3:="$HOME/.ssh/id_rsa"}
 }
 
 # Mac OS especific
@@ -88,15 +69,14 @@ if [[ "$OSTYPE" == darwin* ]]; then
 	# shadow bsd man pages with gnu ones, if findable
   MANPATH="$(find $(brew --prefix) -name man | tr '\n' ':')$MANPATH"
   MANPATH="$(find $(brew --prefix) -name gnuman | tr '\n' ':')$MANPATH"
-
 	export MANPATH
 
   # following the brew instructions...
-  sudo pkill ssh-agent
-  eval $(ssh-agent) > /dev/null 2>&1
+  # sudo pkill -KILL ssh-agent
+  # eval $(ssh-agent -s) > /dev/null 2>&1
 
   # alias it
-  alias ressh-agent='sudo pkill ssh-agent; eval $(ssh-agent)'
+  alias ressh-agent='sudo pkill ssh-agent; eval $(ssh-agent -s)'
 
   function cleanup {
     echo "Killing SSH-Agent"
@@ -126,7 +106,7 @@ if [[ "$OSTYPE" == darwin* ]]; then
 
   # nvm
   type nvm &> /dev/null ||                                             \
-  {                                                                    \
+  (                                                                    \
     git                                                                \
       clone https://github.com/creationix/nvm.git                      \
       $HOME/.nvm                                                       \
@@ -134,6 +114,6 @@ if [[ "$OSTYPE" == darwin* ]]; then
     cd ~/.nvm                                                      &&  \
     git checkout `git describe --abbrev=0 --tags` &> /dev/null     &&  \
     cd;                                                                \
-  }
+  ) &!
 
 fi
