remove dead stuff and fix indentation

diff --git a/runcoms/zshrc b/runcoms/zshrc
--- a/runcoms/zshrc
+++ b/runcoms/zshrc
@@ -7,10 +7,10 @@
 
 # Source Prezto.
 if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
-  . "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
+    . "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
 
-  # source custom completions
-  . "${ZDOTDIR:-$HOME}/.zprezto/custom/completions/tmuxinator.zsh"
+    # source custom completions
+    . "${ZDOTDIR:-$HOME}/.zprezto/custom/completions/tmuxinator.zsh"
 fi
 
 # Customize to your needs...
@@ -19,7 +19,7 @@ alias grep="grep --color=always"
 
 function sshmount() {
 
-  command -v sshfs || { echo 'sshfs could not be found.' && return 1; }
+    command -v sshfs || { echo 'sshfs could not be found.' && return 1; }
 
     sshfs "$1" "$2"                                  \
         -o reconnect                                 \
@@ -33,96 +33,62 @@ function sshmount() {
 # Mac OS especific
 if [[ "$OSTYPE" == darwin* ]]; then
 
-  # Homebrew
-  if type brew &> /dev/null; then
+    # Homebrew
+    if type brew &> /dev/null; then
 
-      ( brew update && brew upgrade ) &> /dev/null &!
+        ( brew update && brew upgrade ) &> /dev/null &!
 
-      dest="/usr/local/share/zsh/site-functions/brew_zsh_completion.zsh"
-      target="$(brew --prefix)/Library/Contributions/brew_zsh_completion.zsh"
+        dest="/usr/local/share/zsh/site-functions/brew_zsh_completion.zsh"
+        target="$(brew --prefix)/Library/Contributions/brew_zsh_completion.zsh"
 
-      if [[ ! -h "$dest" ]]; then
-          ln -s "$target" "$dest"
-      fi
-  else
-      url="https://raw.githubusercontent.com/Homebrew/install/master/install"
-      (
-          ruby -e "$(curl -fsSL "$url" )" &> /dev/null;
+        if [[ ! -h "$dest" ]]; then
+            ln -s "$target" "$dest"
+        fi
+    else
+        url="https://raw.githubusercontent.com/Homebrew/install/master/install"
+        (
+            ruby -e "$(curl -fsSL "$url" )" &> /dev/null;
 
-          dest="/usr/local/share/zsh/site-functions/brew_zsh_completion.zsh"
-          target="$(brew --prefix)/Library/Contributions/brew_zsh_completion.zsh"
+            dest="/usr/local/share/zsh/site-functions/brew_zsh_completion.zsh"
+            target="$(brew --prefix)/Library/Contributions/brew_zsh_completion.zsh"
 
-          if [[ ! -h "$dest" ]]; then
-              ln -s "$target" "$dest"
-          fi
-      ) &!
-  fi
+            if [[ ! -h "$dest" ]]; then
+                ln -s "$target" "$dest"
+             fi
+        ) &!
+    fi
 
-  # only if `homebrew` is installed
-  if command -v brew >/dev/null 2>&1; then
-      # Load rupa's z if installed
-      if [ -f $(brew --prefix)/etc/profile.d/z.sh ]; then
-        [ -f "$HOME/.z" ] || touch "$HOME/.z"
-        . $(brew --prefix)/etc/profile.d/z.sh
-      fi
-  fi
+    # only if `homebrew` is installed
+    if command -v brew >/dev/null 2>&1; then
+        # Load rupa's z if installed
+        if [ -f $(brew --prefix)/etc/profile.d/z.sh ]; then
+            [ -f "$HOME/.z" ] || touch "$HOME/.z"
+            . $(brew --prefix)/etc/profile.d/z.sh
+        fi
+    fi
 
 	# set MANPATH var. The crap about man.conf
 	# has gotten me tired, and I don't see anything in the
 	# mappings that's not already included before in `man --path`
 	# through MANPATH lines, so just set it to whatever `man --path` is
 	if [ -z "$MANPATH" ]; then
-		  MANPATH=$(man --path)
-  fi
+        MANPATH=$(man --path)
+    fi
 
 	# shadow bsd man pages with gnu ones, if findable
-  MANPATH="$(find $(brew --prefix) -name man | tr '\n' ':')$MANPATH"
-  MANPATH="$(find $(brew --prefix) -name gnuman | tr '\n' ':')$MANPATH"
+    MANPATH="$(find $(brew --prefix) -name man | tr '\n' ':')$MANPATH"
+    MANPATH="$(find $(brew --prefix) -name gnuman | tr '\n' ':')$MANPATH"
 	export MANPATH
 
-  # following the brew instructions...
-  # sudo pkill -KILL ssh-agent
-  # eval $(ssh-agent -s) > /dev/null 2>&1
+    # set java home
+    export JAVA_HOME=$(/usr/libexec/java_home -v 1.8 2> /dev/null)
 
-  # alias it
-  alias ressh-agent='sudo pkill -KILL ssh-agent; eval $(ssh-agent -s)'
-
-  function cleanup {
-    echo "Killing SSH-Agent"
-    kill -9 $SSH_AGENT_PID
-  }
-
-  trap cleanup EXIT
-
-  # chrome related
-  alias chrome="'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'"
-  alias devdocs="chrome --app=http://devdocs.io"
-
-  # set java home
-  export JAVA_HOME=$(/usr/libexec/java_home -v 1.8 2> /dev/null)
-
-  # phpbrew related for mac
-  command -v phpbrew &> /dev/null && phpbrew lookup-prefix homebrew > /dev/null 2>&1
+    # phpbrew related for mac
+    command -v phpbrew &> /dev/null && phpbrew lookup-prefix homebrew > /dev/null 2>&1
 fi
-
-# dnvm
-command -v dnvm.sh &> /dev/null && . dnvm.sh 2> /dev/null
 
 # if phpbrew, source
 . ~/.phpbrew/bashrc &> /dev/null
-
-# nvm, install it if missing
-# the sourcing will be handled by prezto's node module in the next run
-type nvm &> /dev/null ||                                             \
-(                                                                    \
-  command -v git &> /dev/null && git clone                           \
-    https://github.com/creationix/nvm.git                            \
-    $HOME/.nvm                                                       \
-    &> /dev/null                                                 &&  \
-  cd ~/.nvm                                                      &&  \
-  git checkout `git describe --abbrev=0 --tags` &> /dev/null     &&  \
-  cd;                                                                \
-) &!
 
 # up; will be sourced on the next run
 if command -v curl &> /dev/null; then
